### ISSUE TITLE
How to sum digits in a string?

### ISSUE THREAD

**Issue by photex** [luafun/luafun#14]
I've tried the following:

``` lua
local data = "ms0010110"
data:gmatch("%d"):sum() -- runtime error
sum(data:gmatch("%d")) -- runtime error
data:gmatch("%d"):reduce(operation.add, 0) -- runtime error

-- but this works fine
local total = 0
for digit in data:gmatch("%d") do
  total = total + digit
end
```

What have I misunderstood?

For some background info, this script is just parsing the various messages reported over the serial line of some old motion controllers. If the result is > 0 we know that there are still axes reporting activity, otherwise we can proceed with whatever foobarbizbaz needs to happen once the motors are positioned.

**Comment by rohieb** [comment]
`string.gmatch()` does not return an [iterator triplet](https://rtsisyk.github.io/luafun/under_the_hood.html#iterator-triplet), only a function:
```
> return data:gmatch("%d") 
function: 0xf2c2b0
> 
```

I don't know why you can still use `for .. in` with it, but it seems all `fun` functions expect iterator triplets.

The functional way would be to use `filter` instead of `gmatch`:
```lua
local fun = require("fun")
local data = "ms0010110"
fun.filter(function (x) return x >= "0" and x <= "9" end, data):sum()
```

**Comment by Positive07** [comment]
Also gmatch makes C calls which are not compiled by LuaJIT
